language: php
php:
- '5.4'
branches: 
env:
  matrix:
  global:
    secure: ENfmJhCIJKywCmari6hjnL+O7tpAvhrtR02Z0lkQCUG1fz+5/XiN3cm4qgaBhlKtYDiPIS+32y/8iKDZzOYnUkmb2v+Q6vwUnP0Le1nluAqseVpEBKP29dvs6hVe+FX5SVT7FXdjAa6EVjnUxCDL7BDt09xOb4+6UbJo55LvhJSvhmPMqGhEIlVAzkKucMne+UlEsVZdc1WzHe97tuSuokWWczfs9AltwoZWeoavL19HYA7j9Ca1sqxjbiDgyUGyDiUhBeASbtc4Z+zgpaSCbgOLOYSS59nc1eV1Z78srhpBJpoHY2+avJ4aYTVUpcQrzPIdLl+uDyisoThrSI4gTUWB1w+caMoooDG5Ajg8tzSypNh5azn1Pn5Q4HHZ7DbFELBBoyLYudA6TAugcVWJgAhFPFVvLHnvz/YOmt5HxAn4VLq/p21nnj3pj7lDfW+2Z9lgm62Li1r+tYGYlR3Jv7RPxfbZa3yvT3HoDDtaAdmyBzMTf536Ty3OqPRYHqJdF4ExfBlwCZct3HgpRhAdKcNt4lzQyxrKWduMEYuUY5HTvnDBA4pfIOyceiBhdSKmx6p6mo/OsfAw/FMvDQjKd2zY3a1EDI+lR2/WemhxRjdfm0sSIDjfimiSsXBTKiW/AmYNDn1Rs+g5VS8QXTkDcxo050yfw7CJ1nSxledyzD8=
before_script:
- composer self-update
- composer install --no-interaction
script:
- phpunit --configuration phpunit.xml
after_success:
- bash deploy/build_success.sh;

after_failure: 
notifications:
  email:
    recipients:
    - alanmanderson@gmail.com
    on_success: always
    on_failure: always
